affinity: {}

image:
  registry: gcr.io/codefresh-inc
  name: codefresh/mdb-query-killer

# dockerConfigB64: 

config: |
  {
    "mongoURI": "mongodb://root:password@localhost:27017/admin?retryWrites=true&w=majority",
    "thresholdSeconds": 90,
    "checkIntervalSeconds": 30,
    "killFilter": {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": ["query"]
          }
        },
        "additionalProperties": true
    },
    "recordAllLongOps": true,
    "longOpsDB": "operations",
    "longOpsCollection":  "long-queries",
    "killedOpsCollection": "killed-queries",
    "killingEnabled": true,
    "slackHookURL": "https://hooks.slack.com/services/ASDSHHH21/VSBE0S22S/dummyRSqwDqweqwWWLms123123"
  }

addons:
  collscanOps:
    enabled: true
    image:
      registry: gcr.io/codefresh-inc
      name: codefresh/collscan-ops-checker
    config: |
      {
        "scanIntervalSec": 3600,
        "slackHookURL": "https://hooks.slack.com/services/DUMMY/HOOK/TokeNasdqw4623542dsfjk",
        "atlasAPI": {
            "groupID": "5ed4aqew1ecc9e2ee2e3qhuc",
            "clusterHostName": "some-db-shard-00-00.1dptz.gcp.mongodb.net",
            "publKey": "mqkqyubj",
            "privKey": "dummy-key2-qwg4-sdg7-qwe47rgh0000"
        }
      }