apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}
    version: {{ .Chart.Version }}
    AppVersion: {{ .Chart.AppVersion }}
    release: {{ $.Release.Name  | quote }}
    heritage: {{ $.Release.Service  | quote }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        chart: {{ $.Chart.Name }}
        version: {{ .Chart.Version }}
        AppVersion: {{ .Chart.AppVersion }}
        heritage: {{ $.Release.Service  | quote }}
        revision: {{ $.Release.Revision | quote }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 0
        fsGroup: 0
        runAsUser: 1000
      affinity:
{{ toYaml $.Values.affinity | indent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ $.Values.container.image.registry }}/{{ $.Values.container.image.name }}:{{ $.Values.container.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: Always
        args: ["/etc/mdb-query-killer/config.json"]
        volumeMounts:
          - name: config
            mountPath: /etc/mdb-query-killer/config.json
            subPath: config.json
      {{- if $.Values.addons.collscanOps.enabled }}
      - name: collscan-ops
        image: "{{ $.Values.addons.collscanOps.image.registry }}/{{ $.Values.addons.collscanOps.image.name }}:{{ $.Values.addons.collscanOps.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: Always
        args: ["/etc/collscan-ops/config.json"]
        volumeMounts:
          - name: addon-collscan-ops-config
            mountPath: /etc/collscan-ops/config.json
            subPath: collscan-ops-config.json
      {{- end }}
      volumes:
      - name: config
        secret:
          secretName: {{ .Chart.Name }}
      {{- if $.Values.addons.collscanOps.enabled }}
      - name: addon-collscan-ops-config
        secret:
          secretName: {{ .Chart.Name }}
      {{- end }}
