apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    AppVersion: {{ .Chart.AppVersion }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  mongo-uri: {{ .Values.config.mongoURI | quote }}  