apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    AppVersion: {{ .Chart.AppVersion }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  config.json: | 
{{ .Values.config | indent 4 }}
  collscan-ops-config.json: | 
{{ .Values.addons.collscanOps.config | indent 4 }}