global: {}

container:
  image:
    registry: us-docker.pkg.dev/codefresh-enterprise/gcr.io
    name: codefresh/mdb-query-killer

imagePullSecrets:
  - name: codefresh-registry

affinity: {}
tolerations: []
nodeSelector: {}

resources: {}

config: |
  {
    "mongoURI": "mongodb://root:password@localhost:27017/admin?retryWrites=true&w=majority",
    "thresholdSeconds": 30,
    "killThresholdSeconds": 90,
    "checkIntervalSeconds": 15,
    "killFilter": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "op": {
              "type": "string",
              "enum": [
                "query"
              ]
            }
          },
          "additionalProperties": true
        },
        {
          "type": "object",
          "properties": {
            "op": {
              "type": "string",
              "enum": [
                "command"
              ]
            },
            "command": {
              "type": "object",
              "anyOf": [
                { "required": ["explain"] },
                { "required": ["count"] },
                { "required": ["aggregate"] }
              ],
              "additionalProperties": true
            }
          },
          "additionalProperties": true
        }
      ]
    },
    "recordAllLongOps": true,
    "longOpsDB": "operations",
    "longOpsCollection":  "long-queries",
    "killedOpsCollection": "killed-queries",
    "killingEnabled": true,
    "slack": {
      "webhookUrl": "https://hooks.slack.com/services/ASDSHHH21/VSBE0S22S/dummyRSqwDqweqwWWLms123123",
      "channels": {
        "alerts": "atlas-db-killed-ops",
        "warnings": "atlas-db-long-ops"
      }
    }
  }

# Reference to a secret containing the config.json
configSecretName: ""

addons:
  collscanOps:
    enabled: true
    image:
      registry: gcr.io/codefresh-inc
      name: codefresh/collscan-ops-checker
    config: |
      {
        "scanIntervalSec": 3600,
        "slackHookURL": "https://hooks.slack.com/services/DUMMY/HOOK/TokeNasdqw4623542dsfjk",
        "atlasAPI": {
            "groupID": "5ed4aqew1ecc9e2ee2e3qhuc",
            "clusterHostName": "some-db-shard-00-00.1dptz.gcp.mongodb.net",
            "publKey": "mqkqyubj",
            "privKey": "dummy-key2-qwg4-sdg7-qwe47rgh0000"
        }
      }
