version: "1.0"
stages:
  - clone
  - prepare
  - deploy
steps:

  main_clone:
    title: 'Cloning main repository...'
    stage: clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: ${{GIT_CONTEXT}}

  prepare_values:
    image: codefresh/cli
    stage: prepare
    commands:
      - codefresh get context ${{VALUES_SHRD_CTX_NAME}} --decrypt --output=yaml | yq -r .spec.data > ${{VALUES_FILEPATH}} 

  helm_deploy:
    image: alpine/helm:3.3.4
    stage: deploy
    commands:
      - if [[ ${CF_BRANCH} != "master" ]]; then export IMAGE_TAG=${CF_BRANCH_TAG_NORMALIZED}; fi
      - |-
        helm upgrade ${{RELEASE_NAME}} ./chart \
        --install \
        --namespace ${{NAMESPACE}} \
        --atomic \
        --kube-context ${{TARGET_CLUSTER}} \
        -f ${{VALUES_FILEPATH}} \
        --set image.tag=${IMAGE_TAG} \
        --set addons.collscanOps.image.tag=${IMAGE_TAG}